trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Linux_machine'
    backendServiceArm: 'wif_automatic'
    backendAzureRmResourceGroupName: 'rg-backend'
    backendAzureRmStorageAccountName: 'bacnendktvstr'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Linux_machine'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'wif_automatic'

- task: PowerShell@2
  displayName: detect terraform changes
  inputs:
    targetType: 'inline'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Linux_machine'
    script: |
      $plan = terraform show -json tfplan | ConvertFrom-Json
      $actions = $plan.resource_changes | ForEach-Object { $_.change.actions }

      if ($actions -contains "create" -or $actions -contains "update" -or $actions -contains "delete") {
          Write-Host "##vso[task.setvariable variable=anyTfChanges]true"
      }

- task: TerraformTask@5
  displayName: terraform apply
  condition: eq(variables['anyTfChanges'], 'true')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Linux_machine'
    commandOptions: 'tfplan'
    environmentServiceNameAzureRM: 'wif_automatic'