trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "Current directory:"
    pwd
    echo "List of files:"
    ls -R
  displayName: Debug Repository Structure
- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: '1.6.6'

- script: |
    terraform version
    terraform init \
      -backend-config="resource_group_name=rg-backend" \
      -backend-config="storage_account_name=bacnendktvstr" \
      -backend-config="container_name=tfstate" \
      -backend-config="key=terraform.tfstate"
  workingDirectory: $(System.DefaultWorkingDirectory)/Linux_machine
  displayName: Terraform Init
    
- task: TerraformTaskV1@0
  displayName: terraform plan -out=tfplan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/14feb/Linux_machine'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'wif_tf_2026'

- task: PowerShell@2
  displayName: detect any terraform change
  inputs:
    targetType: 'inline'
    script: |
      # Write-Host "LASTEXITCODE : $LASTEXITCODE"
      $plan = $(terraform show -json tfplan | ConvertFrom-Json)
      $actions = $plan.resource_changes.change.actions
      Write-Host "Terraform actions : $actions"
      if (($actions -contains 'create') -or ($actions -contains 'delete') -or ($actions -contains 'update'))
      {
        Write-Host "Terraform will perform the following actions : $actions"
        Write-Host "##vso[task.setvariable variable=anyTfChanges;]true"
      }
      else
      {
        Write-Host "There is no change detected in Terraform tfplan file"
      }
    workingDirectory: '$(System.DefaultWorkingDirectory)/14feb/Linux_machine'

- task: TerraformTaskV1@0
  displayName: terraform apply tfplan
  condition: eq(variables.anyTfChanges, true)
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/main/14feb/Linux_machine'
    commandOptions: 'tfplan'
    environmentServiceNameAzureRM: 'wif_automatic'